spring.application.name=store
Kết nối MySQL / TiDB (Hỗ trợ đọc biến môi trường khi deploy lên Render)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root@123}



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Port linh hoạt trên Render
server.port=${PORT:8080}


# Cho phép Spring tự động tạo bảng (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




