spring.application.name=store
# Kết nối MySQL / TiDB (Hỗ trợ đọc biến môi trường khi deploy lên Render)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root@123}

#spring.datasource.url=${DB_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY}
#spring.datasource.username=${DB_USERNAME:21dzVviYtsSGeXU.root}
#spring.datasource.password=${DB_PASSWORD:GQwQd0MnbSu80E2M}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Port linh hoạt trên Render
#server.port=${PORT:8080}

server.port=8080

# Cho phép Spring tự động tạo bảng (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




